# Generated by Django 4.2.6 on 2023-11-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0003_cipher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cipher',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
