# Generated by Django 4.2.7 on 2023-11-19 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphers',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='cipher_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
