# Generated by Django 4.2.6 on 2023-12-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0008_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cipher_images/'),
        ),
    ]
