# Generated by Django 4.2.6 on 2023-12-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0009_ciphers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciphers',
            name='image',
        ),
        migrations.AddField(
            model_name='ciphers',
            name='post_cipher_image',
            field=models.ImageField(blank=True, null=True, upload_to='cipher_img/'),
        ),
    ]
