# Generated by Django 4.2.6 on 2023-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0010_remove_ciphers_image_ciphers_post_cipher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciphers',
            name='post_cipher_image',
        ),
        migrations.AddField(
            model_name='ciphers',
            name='cipher_post',
            field=models.ImageField(blank=True, null=True, upload_to='cipher_images/'),
        ),
    ]
