# Generated by Django 4.2.6 on 2023-12-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0011_remove_ciphers_post_cipher_image_ciphers_cipher_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciphers',
            name='cipher_post',
        ),
    ]
